<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="XIPL9218" name="com.mediaservices.c2c.talent.exception.GlobalExceptionHandlerTest" tests="7" failures="0" timestamp="2 Nov 2018 06:55:51 GMT" time="0.922" errors="0">
  <testcase name="handleValidationException" time="0.779" classname="com.mediaservices.c2c.talent.exception.GlobalExceptionHandlerTest"/>
  <testcase name="handleBindException" time="0.125" classname="com.mediaservices.c2c.talent.exception.GlobalExceptionHandlerTest"/>
  <testcase name="testHandleHttpMessageNotReadableException" time="0.004" classname="com.mediaservices.c2c.talent.exception.GlobalExceptionHandlerTest"/>
  <testcase name="testTalentApplicationExceptionHandlerWithField" time="0.003" classname="com.mediaservices.c2c.talent.exception.GlobalExceptionHandlerTest"/>
  <testcase name="testExceptionHandler" time="0.002" classname="com.mediaservices.c2c.talent.exception.GlobalExceptionHandlerTest"/>
  <testcase name="testTalentApplicationExceptionHandler" time="0.003" classname="com.mediaservices.c2c.talent.exception.GlobalExceptionHandlerTest"/>
  <testcase name="handleInvalidArgumentException" time="0.006" classname="com.mediaservices.c2c.talent.exception.GlobalExceptionHandlerTest"/>
</testsuite> <!-- com.mediaservices.c2c.talent.exception.GlobalExceptionHandlerTest -->
